samples:
  app:
    - name: api-sample
      image: api-sample:0.2.0
      replicas: 2
      service:
        type: ClusterIP
        port: 8000
      ingress:
        enabled: true
        host: api-sample.local
        path: /
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      hpa:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilizationPercentage: 60
      env:
        - name: ENVIRONMENT
          value: "development"
        - name: DEBUG
          value: "true"
      liveness:
        enabled: true
        path: /healthz
        delay: 10
        period: 30
      readiness:
        enabled: true
        path: /healthz
        delay: 10
        period: 30
